добавил pathlib
MaxKuklaVod/P3lv1C pull request #27
Opened 2024-03-04 13:54 UTC by m513t20

тоже минорная косметика

2024-03-04 14:50 UTC, 1ffycat requested changes
Замени `os.path.join` и можно мержить

2024-03-04 14:50 UTC, 1ffycat commented on .gitignore
Опять .gitignore огребает :)

2024-03-04 14:50 UTC, 1ffycat commented on STT.py
> +    adress = os.path.join(Path(__file__).parent, out)
Вместо `os.path.join` юзай оператор `/` из pathlib

https://docs.python.org/3/library/pathlib.html#operators

2024-03-07 03:32 UTC, jezvgg commented on STT.py
> +    adress = os.path.join(Path(__file__).parent, out)
либо можно приводить к классу Path вместо os.path.join.

2024-03-07 10:24 UTC, m513t20 commented on STT.py
> +    adress = os.path.join(Path(__file__).parent, out)
Небольшая проблема. 

Делал через /, делал через purepath, делал через path(file). 

Оно не работает со speech recognition, скорее всего поэтому и в примере работы алгоритма всё было написано через os.

При попытки сделать чистый pathlib выдаётся 
![image](https://github.com/MaxKuklaVod/P3lv1C/assets/150217949/2d6fc1f0-f1e4-475e-affa-1fe4fb321d0f)

2024-03-14 09:51 UTC, 1ffycat commented on STT.py
> +    adress = os.path.join(Path(__file__).parent, out)
Вопрос мб дурацкий, но ты Path к str преобразовать не пробовал?

2024-03-26 03:28 UTC, closed without merging